#!/usr/bin/env python3

# Description: Convert structures from dynamo's crd to pdb
# Last update: 23-03-2022

import argparse
import os

from pdb4all import PDB

parser = argparse.ArgumentParser(prog='pdb2crd',
                                 description='Convert structures from dynamo\'s crd',
                                 formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('infile', metavar='.crd', type=str, nargs='+', default=[],
                    help='input crd file, can be multiple')
parser.add_argument('-o', '--out', metavar='.pdb', type=str, default='', required=False,
                    help='output pdb file, if multiple input files this option is ignored')
args = parser.parse_args()

m = PDB()
for infile in args.infile:
    m.__init__()
    m.read(infile)
    basein, extin = os.path.splitext(infile)
    outfile = args.out if args.out and len(args.infile) == 1 else basein + '.crd'
    m.write(outfile)
    print(f"{infile} -> {outfile}")
