#!/usr/bin/env python3

# Description: Dump frames from a dcd trajectory
# Last update: 07-09-2022

import sys
import argparse

from ecmb import Molec


# Parser
parser = argparse.ArgumentParser(prog='frdump',
                                 description='dump frames from a dcd trajectory')
parser.add_argument('--fr', metavar='#', type=int, nargs='+', required=True,
                    help='frame to dump')
parser.add_argument('--crd', metavar='.crd', type=str, required=True,
                    help='coordinates file')
parser.add_argument('--dcd', metavar='.dcd', type=str, required=True,
                    help='tajectory file')
parser.add_argument('--basename', metavar='<>', type=str,
                    help='basename path for output files, will be followed by frame number and .crd extension (def: fr-)',
                    default='fr-')
args = parser.parse_args()

frames = set(args.fr)
frames_max = max(frames)
basename = args.basename

# read system
m = Molec()
m.load_crd(args.crd)
m.dcd_read(args.dcd)

# dump specified frames
n_dcd = 0
while m.dcd_next() and n_dcd <= frames_max:
    n_dcd += 1
    if n_dcd in frames:
        outfile=f"{basename}{n_dcd}.crd"
        m.save_crd(outfile)
        sys.stdout.write(f"{n_dcd} --> {outfile} \n")
