#!/usr/bin/env python3

# Description: Dump frames from a dcd trajectory
# Last update: 16-05-2022

import sys
import argparse

import ecmb


# Parser
parser = argparse.ArgumentParser(prog='frdump',
                                 description='dump frames from a dcd trajectory')
parser.add_argument('--fr', metavar='#', type=int, nargs='+', required=True,
                    help='frame to dump')
parser.add_argument('--crd', metavar='.crd', type=str, required=True,
                    help='coordinates file')
parser.add_argument('--dcd', metavar='.dcd', type=str, required=True,
                    help='tajectory file')
parser.add_argument('--basename', metavar='<>', type=str,
                    help='basename path for output files, will be followed by frame number and .crd extension (def: fr-)',
                    default='fr-')
args = parser.parse_args()

frames = set(args.fr)
basename = args.basename

# read system
m = ecmb.Molec()
m.load_crd( args.crd )
m.dcd_read( args.dcd )

# dump specified frames
n_dcd = 0
while( m.dcd_next() ):
    n_dcd+=1
    if n_dcd in frames:
        outfile=f"{basename}{n_dcd}.crd"
        m.save_crd(outfile)
        sys.stdout.write(f"{n_dcd} --> {outfile} \n")
        # exit if last frame
        if n_dcd == max(frames):
            sys.exit(0)
