#!/usr/bin/env python3

# Description: Dump frames from a dcd trajectory
# Last update: 28-04-2023

import sys
import argparse

from pdb4all import Traj


# Parser
parser = argparse.ArgumentParser(prog='frdump',
                                 description='dump frames from a dcd trajectory')
parser.add_argument('--fr', metavar='#', type=int, nargs='+', required=True,
                    help='frame to dump')
parser.add_argument('--crd', metavar='.crd', type=str, required=True,
                    help='coordinates file')
parser.add_argument('--dcd', metavar='.dcd', type=str, required=True,
                    help='tajectory file')
parser.add_argument('--basename', metavar='<>', type=str,
                    help='basename path for output files, will be followed by frame number and .crd extension (def: fr-)',
                    default='fr-')
args = parser.parse_args()

# read system
m = Traj()
m.read_dcd(args.dcd, args.crd)

# dump specified frames
for n in sorted(args.fr):
    if n > m.nframes:
        sys.stderr.write(f"WARNING: Skipping frame {n} greater than trajectory ({m.nframes})\n")
        continue
    filename = f"{args.basename}{n}.crd"
    m.nframe(n).write_crd(filename)
    sys.stdout.write(f"{n} --> {filename} \n")
