#!/usr/bin/env python3

# Description: Convert structures from pdb to dynamo's crd
# Last update: 23-03-2022

import argparse
import os

from pdb4all import PDB

parser = argparse.ArgumentParser(prog='pdb2crd',
                                 description='Convert structures to dynamo\'s crd',
                                 formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('infile', metavar='.pdb', type=str, nargs='+', default=[],
                    help='input pdb file, can be multiple')
parser.add_argument('-o', '--out', metavar='.crd', type=str, default='', required=False,
                    help='output crd file, if multiple input files this option is ignored')
parser.add_argument('--simple', action='store_false',
                    help='read simplified pdb based on common columns')
args = parser.parse_args()

m = PDB()
for infile in args.infile:
    m.__init__()
    m.read(infile, strict=args.simple)
    m.guess_elements()
    m.guess_segments()
    m.renum_res()
    m.renum_atoms()
    basein, extin = os.path.splitext(infile)
    outfile = args.out if args.out and len(args.infile)==1 else basein + '.crd'
    m.write(outfile, format='crd')
    print(f"{infile} -> {outfile}")
