#!/usr/bin/env python2

# Description: Convert structures from pdb to dynamo's crd
# Last update: 22-12-2020

import os
import sys
import fileinput

import ecmb

# help
if len(sys.argv)<2 or sys.argv[1] in ('-h','--help'):
    sys.stdout.write("""USAGE:    pdb2crd  <.pdb> <...>\n""")
    sys.exit(1)

# process unlimited structures
m=ecmb.Molec()
for element in sys.argv[1:]:
    basename = os.path.splitext(element)[0]
    outname  = basename + ".crd"

    sys.stdout.write(element + " --> " + outname + "\n")

    m.__init__
    m.load_pdb( file )
    m.guess_z()
    m.save_crd( outname )
    m.__del__

    # Edit wrong CL mass
    for line in fileinput.input(outfile, inplace=True):
        sys.stdout.write( line.replace("CL            6","CL           17") )
